apiVersion: v2
appVersion: "1.0"
description: A Helm chart for paymentoutcome web App
name: ccpay-paymentoutcome-web
home: https://github.com/hmcts/ccpay-paymentoutcome-web
version: 0.0.12
dependencies:
  - name: nodejs
    version: 2.4.1
    repository: '@hmctspublic'

